### ISSUE TITLE
Kerberos support for tramp-hdfs

### ISSUE THREAD

**Issue by ghost** [raghavgautam/tramp-hdfs#8]
Are there any plans to support accessing HDFS using Kerberos auth?

Can I do anything to help? I have access to an HDFS which uses Kerberos for auth and have rudimentary elisp skills.

**Comment by ghost** [comment]
Thanks for adding Kerberos support - I have tested it in my setup, and it works as expected; perfect! :+1:

**Comment by raghavgautam** [comment]
@adsj Glad that it worked for you.
